### ISSUE TITLE
Keepassxc over pageant_shm integration doesn't seem to work

### ISSUE THREAD

**Issue by wfthkttn** [masahide/OmniSSHAgent#28] opened 2022-10-17 12:30 UTC
Getting 'Agent protocol error' in Keepassxc while trying to do so.
I lack the understanding of how it works to locate where the error occurs, or it's not working just for me since something else are broken/misconfigured.

Steps to reproduce:

> 
> Run OmniSSHAgent with default config.
> Start KeepassXC with "Use Pageant" selected, Click "OK".
> Get "Agent protocol error." message whenever you try to add keys / open up SSH Agent config.

//  OpenSSH works just fine tho

**Comment by masahide** [comment] 2022-10-17 12:37
I will also check the operation of keeppassxc.
Please wait a moment.

**Comment by masahide** [comment] 2022-10-18 00:12
I got the same error with the procedure.
The cause is not immediately clear, but we believe there is a protocol incompatibility as per the error.
It may take some time to fix.
Please set "Named pipe agent" instead of "Use Pageant" in the OmniSSHAgent settings and use "OpenSSH" in the KeePassXC SSH agent settings.

**Comment by masahide** [comment] 2022-10-22 14:10
The error was due to an incorrect parameter in the API call from the keepassxc side.

[In putty pagent, the thread ID is a string of '%08x'](https://github.com/github/putty/blob/7003b43963aef6cdf2841c2a882a684025f1d806/windows/winpgntc.c#L50), but in

[keepassxc was using the numeric type as a number without converting it to a hexadecimal string](https://github.com/keepassxreboot/keepassxc/blob/develop/src/sshagent/SSHAgent.cpp#L213-L216).

According to the [manual](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createfilemappinga), the last argument of CreateFileMapping is the correct string type.

**Comment by masahide** [comment] 2022-10-22 14:15
Create a keepassxc pullreq...

**Comment by masahide** [comment] 2022-10-23 09:14
https://github.com/keepassxreboot/keepassxc/pull/8619

**Comment by masahide** [comment] 2022-10-28 14:39
Merged by keepassxc

**Comment by masahide** [comment] 2022-10-30 07:20
keepasxc 2.7.4, which resolves this issue  released.
https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.4

**Closed by masahide** 2022-10-30 07:20 UTC
